uqbar-dao/dev-suite

app/ziggurat.hoon

**Problem**:
When running a test-queue with more than one element, after each element is finished, a %ready and then %running status update will be sent.
**Solution**:
Only send %ready once the queue is empty after running the entire test-queue.
**Notes**:
FYI @tadad

ziggurat: give less status updates during %run-queue

---

lib/zig/ziggurat.hoon

**Problem**:
`custom-read` is displayed differently than every other test-step type.
**Solution**:
Make it not special.

ziggurat: make custom-read json not special

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon
ted/ziggurat/test/run.hoon

**Problem**:
Long outputs are elided -- which is good in general, but bad when, e.g., user wants to scry for a long output.
**Solution**:
Allow user to set by adding `settings` state with same defaults as currently.
**Notes**:
Use `%change-settings` to change the settings and `/settings` to scry out current state.

ziggurat: add settings (configure error output length)

---

lib/pyro/pyro.hoon

**Problem**:
Commits are a bit slower than normal commits
**Solution**:
Utilize the rang scry into clay to get it to parity
**Notes**:
this shaves off about ~2s per commit

quick commit working

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon

**Problem**:
Can register but cannot un-register a contract for compilation.
**Solution**:
Add an %unregister poke.
**Notes**:
None

ziggurat: add %unregister-contract-for-compilation

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon

**Problem**:
1. Chain state scrying only gives state.
2. Can't manipulate that data (which is often big). 
**Solution**:
1. Scry now returns tx.s as well. 
2. Add poke similar to %pyro-agent-state with `grab` field.
**Notes**:
FYI @0x70b1a5 see new interface
~~WIP~~

ziggurat: change and make more flexible scrying pyro chain state

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
lib/zink/conq.hoon
readme.md
sur/zig/ziggurat.hoon
zig/configs/zig.hoon
zig/state-views/agent/wallet-metadata-store.hoon
zig/state-views/agent/wallet-our-items.hoon
zig/state-views/chain/chain.hoon
zig/state-views/chain/holder-our.hoon
zig/state-views/chain/source-zigs.hoon
zig/state-views/chain/transactions.hoon

**Problem**:
We want to enable projects to come with pre-loaded state views.
**Solution**:
Add an additional arm to configuration files.
**Notes**:
When the project is loaded, a %state-views card is sent out. The FE should capture this and use it to populate the new project's state views.
However, since the %zig desk is set up before the FE is running, there is a scry `/state-views/[project-name]` that will return a JSONified %state-views update.

ziggurat: default state views

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon

**Problem**:
Annoying for FE to deal with `desk` not having `name`.
**Solution**:
Add `name` field to `desk`.

ziggurat: add `name` field to `desk`

---

app/ziggurat.hoon

**Problem**:
Ships could not be added to %zig project because %zig directory needs a special case to work properly for initial app setup.
**Solution**:
Make special case more specific.

ziggurat: fix adding ships to %zig project

---

app/ziggurat.hoon
lib/zig/ziggurat/threads.hoon

**Problem**:
Running %new-project on a desk that exists but does not have a configuration thread crashes.
**Solution**:
Run +setup-desk rather than creating an empty configuration thread that runs it (and has dependencies that cause crash).
**Notes**:
None.

ziggurat: fix %new-project for existent desks without config

---

app/pyro.hoon
mar/sh.hoon
scripts/commit-and-install-desks.hoon
scripts/commit-base.hoon
scripts/create-desks.hoon
scripts/dummy.hoon
scripts/setup-fakeship.sh

**Problem**:
It is painful to set up a new fakeship every urbit release.
**Solution**:
Make it somewhat less painful by scripting part of it.
**Notes**:
I'd recommend not pointing this script at your main development repositories because it is new.
Usage example:
```bash
mkdir ~/urbit-for-suite-testing
cd ~/urbit-for-suite-testing
mkdir git
./vere -F zod
./setup-fakeship.sh ../zod/ ../git/
```

scripts: add fakeship %suite setup script

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
lib/zig/ziggurat/threads.hoon

**Problem**:
1. State not properly updated upon sync.
2. `/sync-desk-to-vship/[project-name]` scry gives incorrect results when `!=(focused-project project-name)`.
**Solution**:
1. Update the state.
2. Change scry to `/sync-desk-to-vship` and use `focused-project` for `project-name`.
**Notes**:
None.

ziggurat: fix syncing

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
lib/zig/ziggurat/threads.hoon

**Problem**:
Crash on new project with no project desk because we scry for state-views that DNE.
**Solution**:
Check for state-view file existence before attempting to scry out the file contents.
**Notes**:
none

ziggurat: dont crash if state-views file does not exist

---

app/pyre.hoon
app/pyro.hoon
lib/pyro/pyre.hoon

**Problem**:
pyro still uses subscriptions under the hood to communicate with %pyre
**Solution**:
Rip them out and just use pokes
**Notes**:
I don't believe anything other than pyre currently relies on subscriptions in pyro (events/effects emitted from a pyro ship), so this should be a fine change. If I am wrong we should find a way around it.

subscriptions turned into pokes

---

app/ziggurat.hoon
lib/zig/ziggurat/threads.hoon
ted/ziggurat/build.hoon

**Problem**:
We build all registered files on commit, but should only build those that change.
**Solution**:
Use commit-level %diff on %linedb from https://github.com/uqbar-dao/linedb/pull/48
**Notes**:
None

ziggurat: build only changed files on commit

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
lib/zig/ziggurat/threads.hoon
sur/zig/ziggurat.hoon

**Problem**:
We want to support publishing contracts and apps on the live network.
**Solution**:
1. Allow for deploying contracts on the livenet.
2. Re-add %publish-app code.
**Notes**:
I am imagining that we should provide a step-by-step GUI for the simplest possible few cases that users may want. More complex cases are "power user" territory. The cases I came up with to support are:
1. User wants to deploy 0 or 1 contract.
2. User wants to deploy 0 or 1 Gall app.
These are supported by two separate pokes:
1. `%deploy-contract-livenet`, which sends a transaction to the user's wallet to deploy the given contract (the user will then have to use the %wallet to sign and send the transaction to a %sequencer).
2. `%publish-app`, which will create some necessary files if they do not already …

ziggurat: re-add publish

---

app/pyro.hoon
app/ziggurat.hoon
lib/zig/ziggurat.hoon
sur/zig/ziggurat.hoon

**Problem**:
When arvo is upgraded, %pyro does not upgrade %pyro ships. Currently, it resets state to a clean slate. %ziggurat is not informed and has state that still points to no-longer-existing %pyro state.
**Solution**:
Reset to initial %ziggurat state.
**Notes**:
~~WIP~~

ziggurat: reset state on failed %pyro load

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
lib/zig/ziggurat/threads.hoon
sur/zig/ziggurat.hoon

**Problem**:
Arvo changes kill %pyro ships, causing a %pyro and %ziggurat state wipe. We do not want to wipe users' data without asking for their consent.
**Solution**:
Unsync %suite desk and add tools to inform user when updates come in and allow user to manually update.
**Notes**:
A `%suite-update-available` is sent out from our %ziggurat whenever the distributor's %suite desk changes. The FE should display this somehow and inform users of consequences of updating. The FE should also provide a button that send the `%update-suite` poke.
A draft of what we show users about the consequences of updating:
A new version of %suite is available. Updating %suite will wipe your %ziggurat data if arvo has been updated. If you have data you cannot afford to lose, DO NOT UPDATE.
@0x70b1a5

ziggurat: dont auto-sync %suite desk

---

app/ziggurat.hoon
lib/zig/ziggurat.hoon
lib/zig/ziggurat/threads.hoon
sur/zig/ziggurat.hoon
ted/ziggurat/build.hoon

**Problem**:
%save-file always adds to head.
**Solution**:
%save-file has optional `repo-info=(unit repo-info:zig)` field. If supplied, will branch off from that commit. If not supplied, will work from the `repo-info.desk`: if that has head commit, will append to head, else will branch off from the commit in that `repo-info.desk`.
Regardless, the `repo-info.desk` is updated to head of new branch.
**Notes**:
~~WIP~~
~~This should work, but I need to fix %delete-file (which I realized was still using clay).~~
As of f68a247, %delete-file works. It also has a new `repo-info=(unit repo-info:zig)` field.
Now thinking about whether %save-thread and such should also have a `repo-info` field.
Update: for now: no.

ziggurat: improve %save-file

---

app/ziggurat.hoon
lib/zig/ziggurat/threads.hoon

**Problem**:
Branching behavior in %ziggurat is unnecessarily complex.
**Solution**:
Just %branch as soon as we %fetch.
**Notes**:
None.

ziggurat: branch immediately when fetching from remote

---

app/ziggurat.hoon
lib/linedb.hoon
lib/zig/ziggurat.hoon
lib/zig/ziggurat/system-threads.hoon
sur/zig/ziggurat.hoon
ted/ziggurat/build.hoon

**Problem**:
Creating test threads, living in project repo, is annoying when importing new dev repos because the project repo likely lacks sur/lib files that would make writing those test threads easier/possible.
**Solution**:
1. Change %linedb %build to accept a list of repos, and try finding files in increasing index order. From %ziggurat side, when building something in project repo, pass in all dev repos in list as well. (implemented)
2. Add poke taking two repos and copying all shared files from one to the other -- establishing a "source of truth" ~~(forthcoming)~~ (implemented)
**Notes**:
Paired with https://github.com/uqbar-dao/linedb/pull/67
Done as of d376131

ziggurat: building from project repo passes in other repos for deps
